### ISSUE TITLE
SCSS Selectors

### ISSUE THREAD

**Issue by m0ru** [researchstudio-sat/webofneeds#1004]
Our generated won.css contains selectors like the following (due to some inconsiderate use of `@extends` ^^"):

```css
.settings-tab-bar .astb__tabs .need-tab-bar li.ntb__tabs__selected a,
.need-tab-bar .settings-tab-bar .astb__tabs li.ntb__tabs__selected a,
.settings-tab-bar .astb__tabs .main-tab-bar li.mtb__tabs__selected a,
.main-tab-bar .settings-tab-bar .astb__tabs li.mtb__tabs__selected a,
.settings-tab-bar .astb__tabs .create-need-title li.cnt__tabs__selected a,
.create-need-title .settings-tab-bar .astb__tabs li.cnt__tabs__selected a,
.settings-tab-bar .astb__tabs .visitor-title-bar li.vtb__tabs__selected a,
.visitor-title-bar .settings-tab-bar .astb__tabs li.vtb__tabs__selected a,
.settings-tab-bar .astb__tabs li.astb__tabs__selected a {
{ ... }
```

To avoid these, Hugo Giraudel gives a few best-practices on the use of `@extend` [in this article](https://www.sitepoint.com/avoid-sass-extend/) :

*  Make sure the extended selector is present only once in the stylesheet.
* Avoid extending from nested selectors.
*  Avoid chaining @extend directives.
* Don’t try extending from within a media query; it doesn’t work.

The same author also makes a point [here](https://www.sitepoint.com/avoid-sass-extend/) to avoid `@extend` alltogether in favour of `@import` (as it behaves more predictable and the duplicated rules will be compressed away by gzip anyway). 

I think we should adapt these guidelines as future coding practice and **add them to a style-guide** section in the webapp's README.md. Also, someone could go over the generated code and **fix the worst of these selector-blobs**.

Should we ever go for a big rewrite, [css-modules](https://glenmaddern.com/articles/css-modules) ([try them](http://plnkr.co/edit/FbcJpb?p=preview)) and [postcss](https://github.com/postcss/postcss) might be worth considering.

**Comment by m0ru** [comment]
One of the few edge-cases -- that i can tell -- where `@import` fail us, is when we have import from a class with a sibling selector, e.g.:

```scss
/* SCSS: */
.foo + .foo {
  margin-top: 6rem;
  margin-bottom: 6rem;
}

.bar {
  @extend .foo;
}

/* Result: */
.foo + .foo, .bar + .foo, .foo + .bar, .bar + .bar {
  margin-top: 6rem;
  margin-bottom: 6rem;
}
```
**VS**
```scss
/* SCSS: */

@mixin fooMixin {
  & + & {
    margin-top: 6rem;
    margin-bottom: 6rem;
  }
}

.foo {
  @include fooMixin;
}

.bar {
  @include fooMixin;
}

/* Result: */

.foo + .foo {
  margin-top: 6rem;
  margin-bottom: 6rem;
}

.bar + .bar {
  margin-top: 6rem;
  margin-bottom: 6rem;
}
```
As you can see, with `@extend` the object could be used cross-wise, but also the selector has a length of `(n+1)!` when it's extended `n` times. Also, it's a rather rare case, as most of our siblings will be generated with `ng-repeat` and have the same class.
